import csv
import os
import sys
from datetime import datetime
from xml.sax.saxutils import escape

REQUIRED_COLS = [
    "flow_id", "from_edge", "to_edge", "begin", "end",
    "vehs_per_hour", "vehicle_type", "depart_lane", "depart_speed"
]

DEFAULT_VTYPES = {
    "passenger": {"vClass": "passenger"},
    "truck": {"vClass": "truck"},
    "bus": {"vClass": "bus"},
}

def to_int(value: str, col: str) -> int:
    try:
        return int(float(value))
    except ValueError:
        raise ValueError(f"Kolona '{col}' mora biti broj (int/float). Dobio: {value!r}")

def to_float(value: str, col: str) -> float:
    try:
        return float(value)
    except ValueError:
        raise ValueError(f"Kolona '{col}' mora biti broj (float). Dobio: {value!r}")

def read_csv_rows(csv_path: str):
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        missing = [c for c in REQUIRED_COLS if c not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(
                f"CSV nema potrebne kolone: {missing}\n"
                f"Pronađene kolone: {reader.fieldnames}"
            )
        for i, row in enumerate(reader, start=2):  # header=1
            yield i, row

def build_routes_xml(rows, include_vtypes=True) -> str:
    lines = []
    lines.append('<?xml version="1.0" encoding="UTF-8"?>')
    lines.append('<!-- Generated by csv_to_flows.py -->')
    lines.append(f'<!-- Generated at {datetime.now().isoformat(timespec="seconds")} -->')
    lines.append('<routes>')

    if include_vtypes:
        for vt_id, attrs in DEFAULT_VTYPES.items():
            attr_str = " ".join([f'{k}="{escape(str(v))}"' for k, v in attrs.items()])
            lines.append(f'  <vType id="{escape(vt_id)}" {attr_str}/>')
        lines.append("")

    for line_no, r in rows:
        flow_id = r["flow_id"].strip()
        from_edge = r["from_edge"].strip()
        to_edge = r["to_edge"].strip()
        begin = to_int(r["begin"], "begin")
        end = to_int(r["end"], "end")
        vph = to_float(r["vehs_per_hour"], "vehs_per_hour")
        vtype = r["vehicle_type"].strip() or "passenger"
        depart_lane = (r["depart_lane"].strip() or "best")
        depart_speed = (r["depart_speed"].strip() or "random")

        if not flow_id:
            raise ValueError(f"Red {line_no}: flow_id je prazan.")
        if not from_edge or not to_edge:
            raise ValueError(f"Red {line_no}: from_edge/to_edge ne smije biti prazno.")
        if end <= begin:
            raise ValueError(f"Red {line_no}: end mora biti > begin (begin={begin}, end={end}).")
        if vph < 0:
            raise ValueError(f"Red {line_no}: vehs_per_hour ne smije biti negativan.")

        # Ako želiš strogo: provjeri da li vehicle_type postoji u DEFAULT_VTYPES
        # (ili samo pusti SUMO da prihvati ako imaš vType definisan negdje drugo).
        lines.append(
            f'  <flow id="{escape(flow_id)}" '
            f'from="{escape(from_edge)}" to="{escape(to_edge)}" '
            f'begin="{begin}" end="{end}" '
            f'vehsPerHour="{vph:.6g}" '
            f'type="{escape(vtype)}" '
            f'departLane="{escape(depart_lane)}" '
            f'departSpeed="{escape(depart_speed)}"/>'
        )

    lines.append("</routes>")
    return "\n".join(lines) + "\n"

def main():
    if len(sys.argv) < 3:
        print("Upotreba:")
        print("  python 9_scripts/csv_to_flows.py <ulaz.csv> <izlaz_flows.xml> [--no-vtypes]")
        sys.exit(1)

    csv_path = sys.argv[1]
    out_path = sys.argv[2]
    include_vtypes = "--no-vtypes" not in sys.argv[3:]

    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Ne postoji CSV: {csv_path}")

    rows_list = list(read_csv_rows(csv_path))
    xml_text = build_routes_xml(rows_list, include_vtypes=include_vtypes)

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(xml_text)

    print(f"OK: generisan flows fajl -> {out_path}")
    print(f"Broj flow-ova: {len(rows_list)}")

if __name__ == "__main__":
    main()
